version: "3.5"

services:
    yagvc-app:
        build:
            context: "."
            args:
                uid: ${UID}
                devuser: "${DEVUSER}"
        container_name: yagvc-app
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        depends_on:
            db:
                condition: service_healthy
        environment:
            - APACHE_RUN_USER=#${UID}
            - APACHE_RUN_GROUP=#${UID}
        volumes:
            - .:/var/www/html:cached
        networks:
            backend:
                aliases:
                    - yagvc-app

    selenium:
        image: selenium/standalone-chrome:latest
        container_name: selenium
        restart: unless-stopped
        depends_on:
            db:
                condition: service_healthy
            db_test:
                condition: service_healthy
        volumes:
            - "/dev/shm:/dev/shm"
        ports:
            - "4444:4444"
            - "7900:7900"
        networks:
            backend:
                aliases:
                    - selenium

    db:
        image: mysql:8.0
        profiles: ["dev"]
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        container_name: db
        restart: unless-stopped
        ports:
            - "${DB_PORT}:3306"
        expose:
            - "3306"
        volumes:
            - "./docker/db/data:/var/lib/mysql:cached"
            - "./docker/db/backups:/db_backups:cached"
            - "./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf:cached"
            - "./docker/db/sql:/docker-entrypoint-initdb.d/sql:cached"
            - "./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:cached"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        networks:
            backend:
                aliases:
                    - db
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    db_test:
        image: mysql:8.0
        profiles: ["test"]
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        container_name: db_test
        restart: unless-stopped
        expose:
            - "3306"
        volumes:
            - "./docker/db_test/data:/var/lib/mysql:cached"
            - "./docker/db_test/my.cnf:/etc/mysql/conf.d/my.cnf:cached"
            - "./docker/db_test/init.sql:/docker-entrypoint-initdb.d/init.sql:cached"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=db_test
            - MYSQL_USER=db_test
            - MYSQL_PASSWORD=db_test
        networks:
            backend:
                aliases:
                    - db_test
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    backend:
        name: backend-network
